# Generated by Django 3.1.2 on 2021-01-01 16:26

from django.db import migrations, models
import sensors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(verbose_name='date of measurement')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('resistance', models.IntegerField()),
            ],
            bases=(models.Model, sensors.models.SensorBase),
        ),
        migrations.CreateModel(
            name='SensorData_02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(verbose_name='date of measurement')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('resistance', models.IntegerField()),
            ],
            bases=(models.Model, sensors.models.SensorBase),
        ),
        migrations.CreateModel(
            name='SensorData_03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(verbose_name='date of measurement')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('resistance', models.IntegerField()),
            ],
            bases=(models.Model, sensors.models.SensorBase),
        ),
        migrations.CreateModel(
            name='SensorData_04',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(verbose_name='date of measurement')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('resistance', models.IntegerField()),
            ],
            bases=(models.Model, sensors.models.SensorBase),
        ),
        migrations.CreateModel(
            name='SensorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('descr', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=16)),
                ('pin_bcm', models.IntegerField()),
            ],
        ),
    ]
