# Generated by Django 2.0.1 on 2018-01-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(default='°C', max_length=16),
            preserve_default=False,
        ),
    ]
