# Generated by Django 2.0.1 on 2018-01-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20180109_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='value',
            new_name='temperature',
        ),
        migrations.AddField(
            model_name='measurement',
            name='resistance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
