# Generated by Django 2.0.1 on 2018-02-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0002_auto_20180219_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('descr', models.CharField(max_length=255)),
                ('logic', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motors.Rule')),
            ],
        ),
    ]
