# Generated by Django 2.0.1 on 2018-01-12 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('descr', models.CharField(max_length=255)),
                ('last_toggle', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Toggle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(verbose_name='date published')),
                ('state', models.BooleanField(verbose_name='Status')),
                ('toggle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motors.Motor')),
            ],
        ),
    ]
