# Generated by Django 3.1.2 on 2021-01-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('descr', models.CharField(max_length=255)),
                ('last_toggle', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('descr', models.CharField(max_length=255)),
                ('logic', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Toggle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(verbose_name='date published')),
                ('state', models.BooleanField(verbose_name='Status')),
                ('rule', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='motors.rule')),
                ('toggle', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motors.motor')),
            ],
        ),
        migrations.CreateModel(
            name='RuleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('descr', models.CharField(max_length=255)),
                ('logic', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
                ('rule_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motors.rule')),
            ],
        ),
    ]
