# Generated by Django 2.0.1 on 2018-02-21 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('descr', models.CharField(max_length=255)),
                ('logic', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RuleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('descr', models.CharField(max_length=255)),
                ('logic', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
                ('rule_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motors.Rule')),
            ],
        ),
        migrations.AlterField(
            model_name='toggle',
            name='toggle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motors.Motor'),
        ),
        migrations.AddField(
            model_name='toggle',
            name='rule',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='motors.Rule'),
        ),
    ]
